version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: 'Disabled'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    image: josineiaraujo/chatwoot-custom:latest

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: 'Disabled'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    image: josineiaraujo/chatwoot-custom:latest
