version: '3'

services:
  rails:
    env_file: .env.production
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: 'Disabled'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    image: ${CHATWOOT_IMAGE_NAME:-josineiaraujo/chatwoot-custom}:${CHATWOOT_IMAGE_TAG:-custom-develop}

  sidekiq:
    env_file: .env.production
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: 'Disabled'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    image: ${CHATWOOT_IMAGE_NAME:-josineiaraujo/chatwoot-custom}:${CHATWOOT_IMAGE_TAG:-custom-develop}
