services:
  base:
    image: ghcr.io/josineiaraujo/chathub-chatwoot-ee:ibsoft-production

  rails:
    image: ghcr.io/josineiaraujo/chathub-chatwoot-ee:ibsoft-production

  sidekiq:
    image: ghcr.io/josineiaraujo/chathub-chatwoot-ee:ibsoft-production
